unique_name: TrainingEN1
object_type: model
label: TrainingEN1
metrics:
  - unique_name: m_factinternetsales_salesamount_sum
    folder: Sale Metrics
  - unique_name: m_factinternetsales_salesamount_avg
    folder: Sales Metric
  - unique_name: m_factinternetsales_orderquantity_sum
    folder: Sales Metric
  - unique_name: m_factinternetsales_taxamt_sum
    folder: Sales Metrics
  - unique_name: m_factinternetsales_customerkey_dc
    folder: Customer Metrics
  - unique_name: m_factinternetsales_customerkey_dce
    folder: Customer Metrics
  - unique_name: m_factinternetsales_sales_reasons_non-null
relationships:
  - unique_name: >-
      factinternetsales_orderdatekey_to_dim_date_day_dimension_dim_date_day_dimension
      Level
    from:
      dataset: factinternetsales
      join_columns:
        - orderdatekey
    to:
      dimension: dim_date_day_dimension
      level: dim_date_day_dimension Level
  - unique_name: >-
      factinternetsales_customerkey_to_Customer Dimension_Customer Dimension
      Level
    from:
      dataset: factinternetsales
      join_columns:
        - customerkey
    to:
      dimension: Customer Dimension
      level: Customer Dimension Level
